### PR TITLE
schreier_sims.jl: correct depth check in push!

### LINKED ISSUE #16: Unexpected behaviour of schreier_sims
We are currently implementing the `iterate` functions for stabilizer chains and have encountered an unusual problem: `schreier_sims` seems to generate wrong results in some cases.

`CGT.schreier_sims([perm"(1,2)", perm"(1,2,3)"])` will yield a stabilizer chain of order 4, whereas
`CGT.schreier_sims([perm"(1,2,3)", perm"(1,2)"])` will yield one of order 6 (which is correct).

This seems to suggest there is something wrong with the `sift` algorithm?

### PR DESCRIPTION
**Pull request by fvanmaele**
As discussed in class today

Fixes #16

### CODE REVIEW

**Comment by fvanmaele** [comment]
Well, this fixes the case described in #16, but breaks all other tests :-(

**Review by kalmarek — APPROVED** [review]

File: src/schreier_sims.jl [hunk 1]
```diff
@@ -39,23 +39,22 @@ function schreier_sims(::Type{T}, S::AbstractVector{P}) where {T<:AbstractTransv
...
 
     for i in start_at_depth:depth(sc)
         T = transversal(sc, i)
-        γ = basis(sc, i)^r
+        β = first(T)
+        γ = action(T)(β, r)
+
         if γ ∉ T
-            return d, r
+            return i, r
```
Comment (kalmarek) [inline src/schreier_sims.jl:50]: maybe this was actually the culprit?
